"""
Embed web/index.html into the firmware as a gzipped byte array (src/webIndex.h).

Runs automatically before every PlatformIO build (see extra_scripts in
platformio.ini), and only rewrites the header when the HTML changed.
Can also be run by hand:  python tools/embed_web.py
"""
import gzip
import os

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(PROJECT_DIR, "web", "index.html")
DST = os.path.join(PROJECT_DIR, "src", "webIndex.h")


def build_header(html: bytes) -> str:
    gz = gzip.compress(html, compresslevel=9, mtime=0)  # mtime=0: same input -> same output
    lines = []
    for i in range(0, len(gz), 20):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")
    return (
        "// GENERATED FILE - do not edit.\n"
        "// Source: web/index.html, regenerated by tools/embed_web.py on every build.\n"
        "#pragma once\n\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        f"// {len(html)} bytes of HTML, {len(gz)} bytes gzipped\n"
        "static const uint8_t WEB_INDEX_HTML_GZ[] = {\n"
        + "\n".join(lines)
        + "\n};\n"
        f"static const size_t WEB_INDEX_HTML_GZ_LEN = {len(gz)};\n"
    )


def main():
    with open(SRC, "rb") as f:
        header = build_header(f.read())
    old = None
    if os.path.exists(DST):
        with open(DST, "r", encoding="utf-8") as f:
            old = f.read()
    if old != header:
        with open(DST, "w", encoding="utf-8", newline="\n") as f:
            f.write(header)
        print(f"embed_web: regenerated {os.path.relpath(DST, PROJECT_DIR)}")


main()
